import React from "react";
import {
  GridComponent,
  ColumnsDirective,
  ColumnDirective,
  Resize,
  Sort,
  ContextMenu,
  Filter,
  Page,
  ExcelExport,
  PdfExport,
  Edit,
  Search,
  Toolbar,
  // Inject,
  Selection,
  EditSettings,
} from "@syncfusion/ej2-react-grids";

import {
  ordersData,
  contextMenuItems,
  ordersGrid,
  customersData,
  customersGrid,
  employeesData,
  employeesGrid,
} from "../data/dummy";
import Header from "../components/Header";
import ChartsHeader from "../UI/Charts/ChartsHeader";

export {
  React,
  GridComponent,
  customersData,
  customersGrid,
  employeesData,
  EditSettings,
  ColumnDirective,
  Selection,
  ChartsHeader,
  employeesGrid,
  ColumnsDirective,
  contextMenuItems,
  Resize,
  Sort,
  ContextMenu,
  Filter,
  Search,
  Page,
  Toolbar,
  ExcelExport,
  PdfExport,
  Edit,
  // Inject,
  ordersData,
  ordersGrid,
  Header,
};
